language: java
jdk:
  - oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - echo "ossrhUsername=${ossrhUsername}" >> $HOME/.gradle/gradle.properties
  - echo "ossrhPassword=${ossrhUsername}" >> $HOME/.gradle/gradle.properties
jobs:
  include:
    - stage: build
      script: ./gradlew build -x test
    - stage: test
      script: ./gradlew test
stages:
  - build
  - test
branches:
  only:
    - master
