language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jobs:
  include:
    - stage: build
      script: ./gradlew build -x test
    - stage: test
      script: ./gradlew test
stages:
  - build
  - test
branches:
  only:
    - master
