language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - echo "ossrhUsername=null" >> ~/gradle/gradle.properties
  - echo "ossrhPassword=null" >> ~/gradle/gradle.properties
jobs:
  include:
    - stage: build
      script: ./gradlew build -x test
    - stage: test
      script: ./gradlew test
stages:
  - build
  - test
branches:
  only:
    - master
