language: java
jdk:
  - oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jobs:
  include:
    - stage: build
      script: ./gradlew build -x test -PossrhUsername=${ossrhUsername} -PossrhPassword={ossrhPassword}
    - stage: test
      script: ./gradlew test -PossrhUsername=${ossrhUsername} -PossrhPassword={ossrhPassword}
stages:
  - build
  - test
branches:
  only:
    - master
